[package]
name = "codon"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
comrak = { version = "0.54.0", default-features = false }
crossterm = "0.29.0"
log = "0.4.34"
notify = "8.2.0"
ratatui = "0.30.2"
simplelog = "0.12.2"
syntect = { version = "5.3.0", default-features = false, features = ["default-fancy"] }
unicode-segmentation = "1.12"
unicode-width = "0.2"
